# Generated by Django 4.1.7 on 2023-03-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('isChosen', models.BooleanField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='BreakIntervals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalMinutes', models.IntegerField(verbose_name=range(0, 1440))),
            ],
        ),
        migrations.CreateModel(
            name='WorkTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalHours', models.IntegerField(verbose_name=range(0, 24))),
            ],
        ),
    ]
